# Generated by Django 3.1.7 on 2021-02-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publication_rename_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Причина отклонения'),
        ),
    ]
